//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesMaterial
    {
        public string ClothesCode { get; set; }
        public int MaterialId { get; set; }
        public double Unit { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Material Material { get; set; }
    }
}
