//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clothes()
        {
            this.ClothesDetails = new HashSet<ClothesDetail>();
            this.ClothesMaterials = new HashSet<ClothesMaterial>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public int KindId { get; set; }
        public double DurationOfMade { get; set; }
    
        public virtual ClothesKind ClothesKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClothesDetail> ClothesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClothesMaterial> ClothesMaterials { get; set; }
        public virtual ClothesStock ClothesStock { get; set; }
    }
}
