//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesDetail
    {
        public string ClothesCode { get; set; }
        public int SizeId { get; set; }
        public decimal PriceIn { get; set; }
        public decimal PriceOut { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual ClothesSize ClothesSize { get; set; }
    }
}
