//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.StaffAttendances = new HashSet<StaffAttendance>();
        }
    
        public int Id { get; set; }
        public string NameKh { get; set; }
        public string NameEn { get; set; }
        public int GenderId { get; set; }
        public string NationalId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string CurrentAddress { get; set; }
        public string Phone { get; set; }
        public int SkillId { get; set; }
        public decimal BasicSalary { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual StaffDeduction StaffDeduction { get; set; }
        public virtual StaffPermission StaffPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendance> StaffAttendances { get; set; }
    }
}
