//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDeduction
    {
        public int StaffId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
        public bool Status { get; set; }
        public int ComputerCode { get; set; }
        public System.DateTime ComputeTime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
