//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffBonu
    {
        public string StaffCode { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public string ComputerCode { get; set; }
        public System.DateTime ComputeTime { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
