//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string NameKh { get; set; }
        public string NameEn { get; set; }
        public int GenderId { get; set; }
        public string NationalId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string CurrentAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SkillId { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual StaffDeduction StaffDeduction { get; set; }
        public virtual StaffPermission StaffPermission { get; set; }
    }
}
